export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const PROCES_ADDED = 'PROCES_ADDED';
export const PROCES_EDITED = 'PROCES_EDITED';
export const CHITANTA_ADDED = 'CHITANTA_ADDED';
export const CHITANTA_EDITED = 'CHITANTA_EDITED';
export const CONTROLOR_ADDED = 'CONTROLOR_ADDED';
export const CONTROLOR_EDITED = 'CONTROLOR_EDITED';

export const PROCES_CLICKED = 'PROCES_CLICKED';
export const CHITANTA_CLICKED = 'CHITANTA_CLICKED';
export const CONTROLOR_CLICKED = 'CONTROLOR_CLICKED';

export const DATE_PICKED = 'DATE_PICKED';